### ISSUE TITLE
"cp: cannot stat ‘some_file.ymd’: No such file or directory" on yamado add

### ISSUE THREAD

**Issue by Katsivelisp** [orbifx/yamado#56]
Hello,

I get this error when I run **yamado add**. Then the .ymd file disappears. I have installed Yamado on Ubuntu.

Any ideas?

Thanks!

**Comment by orbifx** [comment]
Where is the file `some_file.ymd` ? Do you run `yamado add some_file.ymd`?

**Comment by Katsivelisp** [comment]
Yes. In the same folder where the .ymd is. Does it require an absolute path or something?

**Comment by orbifx** [comment]
No need for absolute path, but you can. Files in $HOME/yamado/.. are already added. The command `yamado add` is for something which isn't already in there and you want to add it.

You can add a file manually in the Yamado repository, but you need to follow the rules for naming the directory and date for it. So it's best to use `yamado write` if starting a document from nothing. Then you can edit it directly in the Yamado repository, or use `yamado edit ...`.

**Comment by Katsivelisp** [comment]
Thanks!!

**Comment by orbifx** [comment]
- [ ] Put a guard in `yamado add` to not add from withing $YAMADOFILES.
