### ISSUE TITLE
Change default file editor option

### ISSUE THREAD

**Issue by Katsivelisp** [orbifx/yamado#57]
Hi,

is there a way for me to set a different default file editor for "yamado write -i". Some distros haven't got **vim** pre-installed anyway.

**Comment by orbifx** [comment]
Yes. Yamado uses the conventional `$EDITOR` environment variable.

    export EDITOR=xyz
    yamado write -i

This will only last for that session. If you want to set the default editor for your user permentantly, add the export statement to your `.bashrc`.

Something that came to mind.. you probably can add the export to the `.config/yamado/yamado.conf` file and it will only apply to Yamado, but I've not tested this before.

I will add this in the documentation, under some section on editing.

**Comment by orbifx** [comment]
Added this section: https://github.com/orbifx/yamado/blob/master/doc/yamado.md#text-editor
